<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * C'est ici qu'on stock les requetes sql
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{







}
