<?php

namespace AppBundle\Repository;

/**
 * CoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     *  createQueryBuilder() : constructeur de requetes
     *      definir l'alias de l'entite
     *  methodes reprennent le nom des commandes SQL
     *      select : (si on ne met pas de select ça renvoie tout l'objet)
     *          choix des propriété(s) de l'entité en utilisant l'alias
 *              renvoie un un array de array
     *      where / andWhere / orWhere
     *          utilisation de where en premiere condition
     *          à partir de la deuxieme condition : utilisation de andWhere ou orWhere
     *          utilisation des parametres de la requete
     *
     *  getQuery() : execution de la requete / appel de cette méthode en avant dernière position
     *  recuperation des resultats : derniere position
     *      getResult() : renvoie un  array d'objets
     *
     */
    public function testQuery() { // Cette méthode est équivaut à un findAll

        $query = $this->createQueryBuilder('courses')
            ->select('courses.name')
            ->where('courses.name = :nameParam')
            //->andWhere('courses.name LIKE :nameParam')
            ->setParameters([
                'nameParam'=> 'Coiffeur'
            ])
            ->getQuery()
            ->getResult(); // Renvoie un tableau dans un tableau
            //->getSingleResult(); // Renvoie un simple tableau


        //requête de regroupement
        $query = $this->createQueryBuilder('courses')
            ->getQuery()
            ->getResult()
            ;

        return $query;
    }
}
