<?php

namespace AppBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLivre($id)
    {
        $query = $this->createQueryBuilder('livre')
            ->select('livre.titre,livre.auteur,livre.description,livre.datePubli')
            ->where('livre.id = :nameParam')
            ->setParameters([
                'nameParam'=> $id
            ])
            ->getQuery()
             // Renvoie un tableau dans un tableau
        ->getSingleResult(); // Renvoie un simple tableau
        return $query;
    }
    public  function getTitle ($id) {

        $query = $this->createQueryBuilder('livre')
            ->select('livre.titre')
            ->where('livre.id = :nameParam')
            ->setParameters([
                'nameParam'=> $id
            ])
            ->getQuery()
            // Renvoie un tableau dans un tableau
            ->getSingleResult(); // Renvoie un simple tableau
        return $query;

    }



}
